### ISSUE TITLE
[feature request] add generic oidc laravel plugin to heimdall container

### ISSUE THREAD

**Issue by lknite** [linuxserver/docker-heimdall#105]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Looks like if this were installed on the container then I'd just have to configure it:
https://github.com/furdarius/oidconnect-laravel
------------------------------

## Desired Behavior
I wish to configure heimdall with oidc.

## Current Behavior
By default uses laravel and a local user db.

## Alternatives Considered
There are two other laravel keycloak plugins, those would also work, but generic oidc should work also.  I've tried to modify the container myself, but why not just get it added for everyone...

**Comment by elibrody2** [comment]
Plus one for this

**Comment by lknite** [comment]
Made a video for those considering implementing OIDC in their application:

[OIDC for contributors](https://youtu.be/E3fjncdkaOI)
