### ISSUE TITLE
Error On Install

### ISSUE THREAD

**Issue by skydoy** [linuxserver/docker-heimdall#114]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**DSM6
**CPU architecture:** x86_64/
**How docker service was installed:**

## Docker logs

<html><body>

[custom-init] No custom services found, skipping...
--

[custom-init] No custom services found, skipping...

s6-rc: info: service s6rc-oneshot-runner: starting

s6-rc: info: service s6rc-oneshot-runner successfully started

s6-rc: info: service fix-attrs: starting

s6-rc: info: service 00-legacy: starting

s6-rc: info: service 00-legacy successfully started

s6-rc: info: service fix-attrs successfully started

s6-rc: info: service legacy-cont-init: starting

cont-init: info: running /etc/cont-init.d/01-envfile

cont-init: info: /etc/cont-init.d/01-envfile exited 0

cont-init: info: running /etc/cont-init.d/01-migrations

[migrations] started

[migrations] 01-nginx-site-confs-default: executing...

[migrations] 01-nginx-site-confs-default: succeeded

[migrations] 02-default-location: executing...

[migrations] 02-default-location: succeeded

[migrations] done

cont-init: info: /etc/cont-init.d/01-migrations exited 0

cont-init: info: running /etc/cont-init.d/10-adduser

usermod: no changes

-------------------------------------

          _         ()

         | |  ___   _    __

         | | / __| | |  /  \

         | | \__ \ | | | () |

         |_| |___/ |_|  \__/

Brought to you by linuxserver.io

-------------------------------------

To support LSIO projects visit:

https://www.linuxserver.io/donate/

-------------------------------------

GID/UID

-------------------------------------

User uid:    911

User gid:    911

-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0

cont-init: info: running /etc/cont-init.d/11-folders

cont-init: info: /etc/cont-init.d/11-folders exited 0

cont-init: info: running /etc/cont-init.d/12-samples

cont-init: info: /etc/cont-init.d/12-samples exited 0

cont-init: info: running /etc/cont-init.d/13-nginx

Setting resolver to  1.1.1.1 1.0.0.1

Setting worker_processes to 4

cont-init: info: /etc/cont-init.d/13-nginx exited 0

cont-init: info: running /etc/cont-init.d/14-php

cont-init: info: /etc/cont-init.d/14-php exited 0

cont-init: info: running /etc/cont-init.d/15-keygen

generating self-signed keys in /config/keys, you can replace these with your own keys if required

Generating a RSA private key
Setting permissions

cont-init: info: /etc/cont-init.d/50-config exited 0

cont-init: info: running /etc/cont-init.d/85-version-checks

cont-init: info: /etc/cont-init.d/85-version-checks exited 0

cont-init: info: running /etc/cont-init.d/99-custom-files

[custom-init] No custom files found, skipping...

cont-init: info: /etc/cont-init.d/99-custom-files exited 0

s6-rc: info: service legacy-cont-init successfully started

s6-rc: info: service init-mods: starting

s6-rc: info: service init-mods successfully started

s6-rc: info: service init-mods-package-install: starting

s6-rc: info: service init-mods-package-install successfully started

s6-rc: info: service init-mods-end: starting

s6-rc: info: service init-mods-end successfully started

s6-rc: info: service init-services: starting

s6-rc: info: service init-services successfully started

s6-rc: info: service legacy-services: starting

services-up: info: copying legacy longrun cron (no readiness notification)

services-up: info: copying legacy longrun nginx (no readiness notification)

services-up: info: copying legacy longrun php-fpm (no readiness notification)

services-up: info: copying legacy longrun queue (no readiness notification)

s6-rc: info: service legacy-services successfully started

s6-rc: info: service 99-ci-service-check: starting

[ls.io-init] done.

s6-rc: info: service 99-ci-service-check successfully started

crond[224]: crond (busybox 1.34.1) started, log level 5

[25-Nov-2022 17:05:55] NOTICE: fpm is running, pid 222

[25-Nov-2022 17:05:55] NOTICE: ready to handle connections

   ErrorException 

  file_put_contents(/app/www/storage/framework/cache/data/f4/29/f4296a60f762a0cf41a0e9403543237d19996bf7): Failed to open stream: Permission denied

  at /app/www/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:187

    183▕      * @return int|bool

    184▕      */

    185▕     public function put($path, $contents, $lock = false)

    186▕     {

  ➜ 187▕         return file_put_contents($path, $contents, $lock ? LOCK_EX : 0);

    188▕     }

    189▕ 

    190▕     /**

    191▕      * Write the contents of a file, replacing it atomically if it already exists.

      +9 vendor frames 

  10  /app/www/app/Providers/AppServiceProvider.php:40

      App\Jobs\ProcessApps::dispatch()

      +7 vendor frames 

  18  [internal]:0

      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}()

**Comment by skydoy** [comment]
Hello can anyone address this?

**Comment by aptalca** [comment]
https://info.linuxserver.io/issues/2022-11-25-heimdall/

**Comment by skydoy** [comment]
Thanks
