### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by oreillygshane** [linuxserver/docker-heimdall#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When starting the docker image, the following error appears in the logs:

/etc/s6-overlay/s6-rc.d/init-adduser/run: line 46: lsiown: command not found 

Logs are here:
[LOGS-syno-docker-heimdall-20230820.csv](https://github.com/linuxserver/docker-heimdall/files/12387219/LOGS-syno-docker-heimdall-20230820.csv)

### Expected Behavior

The docker image should start.

### Steps To Reproduce

The the docker image (latest)

### Environment

```markdown
- OS: Synology
- How docker service was installed: Native Synology 'Container Manager' tool
```

### CPU architecture

x86-64

### Docker creation

```bash
Screenshot in comment
```

### Container logs

```bash
N/A
```

**Comment by oreillygshane** [comment]
<img width="979" alt="Screenshot 2023-08-20 at 13 11 19" src="https://github.com/linuxserver/docker-heimdall/assets/15385374/c8a1600a-358b-4e39-aaae-411b36a9bb57">

**Comment by Airwolf1544** [comment]
Same Problem here.. just updated from a 3 Year old Image to latest.. exactle the same issue.
Also a Synolog NAS.

**Comment by j0nnymoe** [comment]
Bug is caused by the Synology gui : https://info.linuxserver.io/issues/2023-05-22-portainer/

**Comment by Airwolf1544** [comment]
Hi,
believe in me... nobody reads, what environments are supported ;-)
I can understand, it's frustrating to get bugs reported, which are bugs from other partys.. 
Everyone get's first to the Software Builder and asks for help.. and if the problem is not there, you search in your (Docker)Environment.. :-) 
Anyway.. thank you for help j0nnymoe!

**Comment by Tieske** [comment]
To get around this, create a new container. Remove the old one.

Synology;
- select the container
- "action" -> "duplicate settings", give it a new name
- stop and delete the existing container
- start the newly duplicated one
