### ISSUE TITLE
[BUG] 500 on items/create

### ISSUE THREAD

**Issue by Gisleburt** [linuxserver/docker-heimdall#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When arriving on a fresh, the homescreen works fine, but clicking 'Add an application here' causes a 500

<img width="1640" alt="Screenshot 2023-09-07 at 01 00 29" src="https://github.com/linuxserver/docker-heimdall/assets/2369524/a4fc2ff2-dfc3-4945-be9f-daa7231c3423">

<img width="1638" alt="Screenshot 2023-09-07 at 01 01 04" src="https://github.com/linuxserver/docker-heimdall/assets/2369524/e96893b0-f433-4ce8-ba5b-7a53aab5d9c9">

### Expected Behavior

I should be able to add an application

### Steps To Reproduce

I am trying to run the container in kubernetes (see below for deployment yaml).

I have tried both 2.5.6 and 2.5.5 (based on a similar sounding bug in linuxserver/Heimdall#1183)

I've also tried with and without the PUID and PGID but its the same either way (also other files have been written to the volume)

Logs:
- no errors in `kubectl logs ...`
- there is no error log file in `/config/log/heimdall`
- `/config/log/nginx/error.log` exists but is empty
- `/config/log/nginx/access.log` shows the 500s but has no useful info about them
- `/config/log/php/error.log` only says fpm is ready

Some possible quirks:
- I'm using an NFS persistent volume however
    - other files have been created perfectly fine
    - 1Gi is assigned but only ~296K is being used
- I'm doing edge TLS decryption handled by cert manager, internal traffic is on 80

With no logs I'm not sure what to go off

### Environment

```markdown
- OS: This... needs some explaining

I'm running a multi arch k3s cluster across several NUCs (amd64) running latest Ubuntu LTS and Pi4's (arm64) running latest Raspbian

_Currently_ the service is running on the NUCs so the architecture is amd64, however, I haven't specified that it needs to run there so it could change.

- How docker service was installed:

k3s using custom Ansible, though this is the only app I've struggled with like this

If you're super curious, its here though some of the README is a bit out of date: https://github.com/gisleburt/homelab
```

### CPU architecture

x86-64

### Docker creation

```bash
---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: heimdall
  name: heimdall
  namespace: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
        - name: heimdall
          image: linuxserver/heimdall:2.5.6
          imagePullPolicy: Always
          ports:
            - name: heimdall
              containerPort: 80
          env:
            - name: TZ
              value: Europe/London
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: config
              mountPath: "/config"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║      
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
New container detected, installing Heimdall
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by Dapolux** [comment]
Hi @Gisleburt, 
I have the same problem on my side, the only way i found to solve it, is having my docker LXC CT as an "Unprivilegied CT".

**Comment by aptalca** [comment]
To clarify, we do not support docker in lxc. Even the proxmox (majority of lxc users seem to be proxmox users based on the issue reports we get) devs recommend against running docker in lxc. So that wouldn't be considered a solution.

For the OP, your issue is likely due to storing the config folder on nfs. We don't support or recommend putting config folders on a remote share (media/data folders are fine). Especially databases do not like that. On k8s, you can either do local or block storage like longhorn.

**Comment by Gisleburt** [comment]
Thanks for the response @aptalca. I'd been wanting to add Longhorn for a little while so this was a nice excuse, wish I'd done it earlier now, it was far easier than my NFS provisioner 😛 . 

![Screenshot 2023-09-21 at 17 39 12](https://github.com/linuxserver/docker-heimdall/assets/2369524/4959427c-da20-484a-bfd4-f242f2937c99)

Unfortunately I still get a 500 and still don't get anything in the logs.

**Comment by Dapolux** [comment]
> To clarify, we do not support docker in lxc. Even the proxmox (majority of lxc users seem to be proxmox users based on the issue reports we get) devs recommend against running docker in lxc. So that wouldn't be considered a solution.
> 
> For the OP, your issue is likely due to storing the config folder on nfs. We don't support or recommend putting config folders on a remote share (media/data folders are fine). Especially databases do not like that. On k8s, you can either do local or block storage like longhorn.

Thanks for the information.

By the way, doing additional tests, even if it's not a recommended solution to use LXC docker, switching from a CT template "turnkey" to a CT template "standard" is solving the issue on my landscape.
All is working fine on my side now.

**Comment by Gisleburt** [comment]
What else can I add to help?

**Comment by j0nnymoe** [comment]
Your issues are probably just because of using k3s. While I've seen users say they have it working, it's not a platform we provide support for.

**Comment by Gisleburt** [comment]
Ok, I'll try something else. Thanks for looking into it.
