### ISSUE TITLE
[BUG] Release 2.5.7 Missing

### ISSUE THREAD

**Issue by mark-monteiro** [linuxserver/docker-heimdall#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

[Version 2.7.7](https://github.com/linuxserver/Heimdall/releases/tag/v2.5.7) of Heimdall was released a month ago, but there has been no related docker release from this repo

### Expected Behavior

There should be a release for version 2.7.7. Perhaps this is because the [latest release](https://github.com/linuxserver/Heimdall/releases/latest) in the Heimdall repo still points to version 2.7.6?

### Steps To Reproduce

N/A

### Environment

```markdown
N/A
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
N/A
```

**Comment by aptalca** [comment]
Thanks for the heads up. Somehow it wasn't marked as latest on GitHub (likely oversight). It is marked now and there should be a new docker build within the hour.
