### ISSUE TITLE
[BUG] Erorr with latest version V2.5.8-ls252 after updating container - Error included in Current behavior section

### ISSUE THREAD

**Issue by tweek11** [linuxserver/docker-heimdall#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Heimdall updated to version V2.5.8-ls252 and upon accessing the container it produces the following error below: 

@extends('layouts.app') @section('content') @include('partials.search') @if($apps->first()) @include('sortable') @else

{!! __('app.dash.no_apps', [ 'link1' => '['.__('app.dash.link1').'](https://192.168.70.20:49157/'.route('items.create',%20[]).')', 'link2' => '['.__('app.dash.link2').'](https://192.168.70.20:49157/)' ]) !!}
@include('add')
@endif @endsection

### Expected Behavior

Open the Heimdall home page without error.

### Steps To Reproduce

Updated from Version V2.5.8-ls250

### Environment

```markdown
- OS: Ubuntu 22.04.4 
- How docker service was installed: Directly from docker repository. no SNAPD items installed on the system.
```

### CPU architecture

x86-64

### Docker creation

```bash
version: '3.9'
services:
    heimdall:
        image: linuxserver/heimdall:latest
        ports:
            - '49157:443'
            - '49156:80'
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/New_York
        volumes:
            - '/home/myusername/docker/heimdall:/config'
        container_name: heimdall
        restart: unless-stopped
```

### Container logs

```bash
[migrations] started

[migrations] 01-nginx-site-confs-default: skipped

[migrations] 02-default-location: skipped

[migrations] done

───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗

      ██║     ██╔════╝██║██╔═══██╗

      ██║     ███████╗██║██║   ██║

      ██║     ╚════██║██║██║   ██║

      ███████╗███████║██║╚██████╔╝

      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io

───────────────────────────────────────

To support LSIO projects visit:

https://www.linuxserver.io/donate/

───────────────────────────────────────

GID/UID

───────────────────────────────────────

User UID:    1000

User GID:    1000

───────────────────────────────────────

using keys found in /config/keys

New container detected, installing Heimdall

[custom-init] No custom files found, skipping...

[ls.io-init] done.
```

**Comment by Neriderc** [comment]
See #143 that was posted just 5 mins before this.

TL:DR; It seems this release broke things, use `image: linuxserver/heimdall:2.5.7` to revert to v2.5.7 which gets it working again.

**Comment by hytrek** [comment]
Same here

**Comment by tweek11** [comment]
I see the other ticket now, sorry about that. There wasn't another ticket when i was gathering the information for the ticket i submitted - other wise i would of just commented on it.

**Comment by Fallenfederation** [comment]
Same issue here 

@extends('layouts.app') @section('content') @include('partials.search') @if($apps->first()) @include('sortable') @else
{!! __('app.dash.no_apps', [ 'link1' => '['.__('app.dash.link1').'](http://xxx.xxx.xxx.xxx:446/'.route('items.create',%20[]).')', 'link2' => '['.__('app.dash.link2').'](http://xxx.xxx.xxx.xxx:446/)' ]) !!}

@include('add')
@endif @endsection

**Comment by MrThorx** [comment]
> I see the other ticket now, sorry about that. There wasn't another ticket when i was gathering the information for the ticket i submitted - other wise i would of just commented on it.
> 
> Additionally - instead of going back to older version of that i was not on 2.5.7 - i just changed latest to the prior tag of V2.5.8-ls251 and it up for the time being.


a stupid question, how can I go back to version V2.5.8-ls251? I use unraid.

**Comment by myozone** [comment]
Same here after overnight update - how do I fix it ?? I use docker on Debian / Portainer



@extends('layouts.app') @section('content') @include('partials.search') @if($apps->first()) @include('sortable') @else
{!! __('app.dash.no_apps', [ 'link1' => '['.__('app.dash.link1').'](http://192.168.2.200:8002/'.route('items.create',%20[]).')', 'link2' => '['.__('app.dash.link2').'](http://192.168.2.200:8002/)' ]) !!}

@include('add')
@endif @endsection

**Comment by KardinalReusen** [comment]
> a stupid question, how can I go back to version V2.5.8-ls251? I use unraid.

Just change the Repository to "lscr.io/linuxserver/heimdall:2.5.7" or whatever version you like.

**Comment by myozone** [comment]
> V2.5.8-ls251

Worked for me 

Thank You !

**Comment by evmolpos** [comment]
just returned to V2.5.8-ls251 till a fix arrives. thanks.

**Comment by jacksonjlee** [comment]
Same issue here. Downgrading back to V2.5.8-ls250 fixed the issue on my system. I did not try any other version, but later versions may also work as intended.

For anyone confused about how to downgrade, the process is outlined on the docker hub page. In my case, my docker compose file now reads:
`image: lscr.io/linuxserver/heimdall:amd64-V2.5.8-ls250`

**Comment by tweek11** [comment]
Thank you for the v2.6.0-ls253 update - everything is back up and running properly using the latest tag in the docker-compose.yml file.

Marking as closed
