### ISSUE TITLE
[BUG] docker tag with different versioning format

### ISSUE THREAD

**Issue by 4s3ti** [linuxserver/docker-heimdall#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Automation tools such as fluxcd detect a container tag `2021.11.28` and use it when version constraints are, for example `>=1.0.0` 

not exactly a bug, and could be fixed by constraining the versions a bit more on fluxcd side, however figured better report in case this is just dangling and the container registry needs some cleanup. 

### Expected Behavior

all image tags following the same versionin

### Steps To Reproduce

`docker pull ghcr.io/linuxserver/heimdall:2021.11.28`

### Environment

```markdown
N/A
```

### CPU architecture

x86-64

### Docker creation

```bash
N/A
```

### Container logs

```bash
N/A
```

**Comment by aptalca** [comment]
https://www.linuxserver.io/blog/docker-tags-so-many-tags-so-little-time#semver-info

**Comment by 4s3ti** [comment]
Alright, now it makes sense. Thank you for the clarification. Should have searched better :)
