### ISSUE TITLE
Help with Setup Tautulli Enhanced App

### ISSUE THREAD

**Issue by itr6** [linuxserver/docker-heimdall#26]
I cannot get my docker install to setup the Tautulli enhanced app. The link works fine to open up Tautulli but that's it. My Pihole enhanced app works great. I have tried setting the secondary URL in the config area to the direct URL and port instead of my Caddy Reverse proxy address. I have even tried setting the secondary URL to the IP address and port. It does not work. I have also tried changing API keys, turning API off and back on again and still nothing.

Can anyone provide any assistance? Is there something within Tautulli I need to setup for this to work?

Thanks.

OS: Ubuntu 16.04.5 LTS
GUI: Heimdall Web UI
Logs: N/A
Symlinks: N/A

**Comment by aptalca** [comment]
Duplicate https://github.com/linuxserver/Heimdall/issues/305
