### ISSUE TITLE
Fresh install broken page

### ISSUE THREAD

**Issue by slimshizn** [linuxserver/docker-heimdall#27]
Using Ubuntu 16.04

![image](https://user-images.githubusercontent.com/23506499/50522043-f5fecf00-0a96-11e9-94a9-2780d1f00fb1.png)

> [cont-init.d] 10-adduser: exited 0.
> 
> 
> [cont-init.d] 20-config: executing... 
> 
> 
> [cont-init.d] 20-config: exited 0.
> 
> 
> [cont-init.d] 30-keygen: executing... 
> 
> 
> generating self-signed keys in /config/keys, you can replace these with your own keys if required
> 
> 
> Generating a RSA private key
> 
> 
> ...................+++++
> 
> 
> .....................................................+++++
> 
> 
> writing new private key to '/config/keys/cert.key'
> 
> 
> -----
> 
> 
> [cont-init.d] 30-keygen: exited 0.
> 
> 
> [cont-init.d] 50-config: executing... 
> 
> 
> [cont-init.d] 50-config: exited 0.
> 
> 
> [cont-init.d] done.
> 
> 
> [services.d] starting services
> 
> 
> [services.d] done.
> 
> 
> [2018-12-28 16:33:35][1] Processing: App\Jobs\ProcessApps
> 
> 
> [2018-12-28 16:34:16][1] Processed:  App\Jobs\ProcessApps

using Linuxserver.io version:- 2.1.12-ls21 Build-date:- 2018-12-22T00:55:51+00:00 on Portainer

I had this working with a previous verison, was advised to remove config and start fresh due to a issue where upgrades broke installs. Removed config (backed up) and this is a fresh install. Cleared browser cache, purged cache on cloudflare and tried other browsers.

**Comment by slimshizn** [comment]
Came from release 71 to this one so I went back to 71 with previous appdata. Went ahead and pulled new release again and it's working. Not sure what happened there but I'll mark this as working/fixed.

**Comment by fweep** [comment]
This is exactly what it looks like to me on a fresh new install. And all the links are broken because they just go to http://heimdall/. I'm sure I'll figure it out soon enough and won't come back here to comment, but there's definitely either something broken out of the box or some caveat about installation that's not covered in the quickstart instructions.
