### ISSUE TITLE
laravel.log grows within the container

### ISSUE THREAD

**Issue by anoma** [linuxserver/docker-heimdall#47]
laravel.log grows within the container

```
root@2245ca0ff4aa:/var/www/localhost/heimdall/storage/logs# ls -alh /var/www/localhost/heimdall/storage/logs/laravel.log 
-rw-r--r-- 1 abc abc 1.1G Jul 11 09:49 /var/www/localhost/heimdall/storage/logs/laravel.log
```

```
root@2245ca0ff4aa:/var/www/localhost/heimdall/storage/logs# wc -l /var/www/localhost/heimdall/storage/logs/laravel.log 
5943956 /var/www/localhost/heimdall/storage/logs/laravel.log
```

Likely something to do with

```
[2019-07-09 05:46:06] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (InvalidArgumentException(code: 0): Log [] is not defined. at /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Log/LogManager.php:168)
```

This appears to be two days of logs.

**Comment by jeremysherriff** [comment]
Something writing to logs with mine, if that helps?
```root@8f63d97a46ca:/# ls -al /var/www/localhost/heimdall/storage/logs/
total 288
drwxrwxr-x 2 abc users   4096 Jul 13 21:03 .
drwxrwxr-x 5 abc users   4096 Jun 23 04:05 ..
-rw-r--r-- 1 abc users 284583 Jul 14 10:10 laravel.log
```

```root@8f63d97a46ca:/# tail /var/www/localhost/heimdall/storage/logs/laravel.log
#46 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#52 /var/www/localhost/heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#53 /var/www/localhost/heimdall/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#54 {main}
"}
```

**Comment by zyphermonkey** [comment]
+1 also having the issue with the laravel.log file growing within the container.

**Comment by j0nnymoe** [comment]
Seems the reason it grows is due apps that have been put into the trash (possibly ones that have been configured incorrectly) delete those and it should stop the log growing.

**Comment by zyphermonkey** [comment]
> Seems the reason it grows is due apps that have been put into the trash (possibly ones that have been configured incorrectly) delete those and it should stop the log growing.

Can you tell me where to find the 'trash'? I don't see anything referencing it in any of the menus.

**Comment by j0nnymoe** [comment]
It will show next to "application list" in the items menu.

**Comment by anoma** [comment]
In my case an enhanced app appeared to work (and in fact did work) but I could not deactivate the slider for it. Once i removed the app and cleared the log the issue never came back.

The important point though is we need to define this log location so that should it happen again the logs do not pollute the container potentially, as would be the case with unRAID, filling up the loopback disk and crashing docker.

I have absolutely no idea where the correct place to set this log location in larval is though.

**Comment by jeremysherriff** [comment]
In my case, once I knew about the log in the container storage (from this issues thread) I simple set that location to be external to the container with a volume bind.  If the log is due to an error in config and uncontrollable, that seems the simplest way to deal with it.

It will be difficult to test - although my enhancedApp pi-hole shortcut did originally work and I'm reasonably sure I deleted the app shortcut in Heimdall at around the time I retired that instance of pi-hole, *but* I had another Heimdall page open/running on a PC I don't use a lot, and that would have still had the original config of the old pi-hole enhancedApp shortcut for a day or so afterwards.  I became aware of that via a netdata alarm for nginx 500 response codes, that lead me to track down what it was (the stale Heimdall page) and simply F5 refresh it.

**Comment by aptalca** [comment]
Just a heads up, I'm submitting PRs to persist the log file in /config
Here's the PR for the development tag: #48 

Since I don't even have a laravel.log on my install, I can't test (I'm assuming it's only created when there are errors).

Can someone make the same change to their init file and test? You can do `docker exec -it heimdall bash` to exec into the container, then edit the init file and restart the container

**Comment by zyphermonkey** [comment]
> Just a heads up, I'm submitting PRs to persist the log file in /config
> Here's the PR for the development tag: #48
> 
> Since I don't even have a laravel.log on my install, I can't test (I'm assuming it's only created when there are errors).
> 
> Can someone make the same change to their init file and test? You can do `docker exec -it heimdall bash` to exec into the container, then edit the init file and restart the container

This works and saves the log file outside of the container.
Because this file can grow  fairly large quickly it might be a good idea to also include some sort of trimming with logrotate or the likes to keep it small and to still keep events around, but at a manageable size.

**Comment by aptalca** [comment]
Thanks for the confirmation. That's a good idea, I'll add it to the logs folder and enable logrotate

**Comment by aptalca** [comment]
@zyphermonkey I updated the PR. It now saves the log under `/config/log/heimdall/laravel.log` along with the other nginx and php logs, and it is rotated at 5MB with 5 compressed copies.

If you can test, we'll merge and submit the same PR to stable

**Comment by aptalca** [comment]
Even if it grows to more than 5MB very quickly, it won't be rotated more frequently than once an hour, because that's how frequently logrotate service checks

**Comment by zyphermonkey** [comment]
I don't think it's checking hourly. I didn't find anything in /etc/crontab.hourly, but I also might be looking in the wrong spot.
I couldn't find where the logrotate service checks interval except for in /etc/logrotate.conf set to weekly. If that is the case then this could possibly grow quite large before being rotated.

In addition would it be better to have this log file in /config/log/heimdall or to keep it in /config/www where it is currently?

**Comment by aptalca** [comment]
@zyphermonkey actually, my mistake. It runs daily. Look under `/etc/periodic/daily`. That's the cron entry for logrotate

**Comment by timdonovanuk** [comment]
My Heimdall page is 920kb on load (according to Chrome dev tools). 

To generate this ~1mb web page, Heimdal:

- stores 448mb of data in my docker volume (which is mostly laravel.log)
- consumes 120mb of RAM

Looking at the ~30 containers I run, Heimdal is probably the most simple in terms of functionality but boy does it consumer more than it's fair share of resources...
