### ISSUE TITLE
Missing Supported Apps in Docker Image

### ISSUE THREAD

**Issue by rigrassm** [linuxserver/docker-heimdall#5]
It looks like there are quite a few Supported Apps listed for the project that are missing from the ones available in the docker image.

Below are the applications that have files in the SupportedApps directory. The one that I initially noticed missing was the NZBHydra application.

```
root@eae1ca5ffd51:/var/www/localhost/heimdall$ ls app/SupportedApps/
Contracts	   Jackett.php	    Netdata.php    Opnsense.php  Plexpy.php	   Radarr.php	Unifi.php
Duplicati.php	   Jdownloader.php  Nextcloud.php  Pfsense.php	 Plexrequests.php  Sabnzbd.php	ruTorrent.php
Emby.php	   Lidarr.php	    Nzbget.php	   Pihole.php	 Portainer.php	   Sonarr.php
HomeAssistant.php  Mcmyadmin.php    Openhab.php    Plex.php	 Proxmox.php	   Traefik.php
```

Not sure if it's just that there hasn't been a release yet that has these application files or if the image just needs a rebuild.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by sparklyballs** [comment]
update the image and container with a new pull
