### ISSUE TITLE
served icons have http schema and cant be accessed behind ssl reverse proxy

### ISSUE THREAD

**Issue by dimagoltsman** [linuxserver/docker-heimdall#61]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

i have a Nginx that handles https. the problem is that there are files served with http schema and blocked due to mixed content by the browse.
also, the page is broken

------------------------------

## Expected Behavior
to be able to access behind reverse proxy with https

## Current Behavior
page is broken

## Environment
**OS:**      Ubuntu
**CPU architecture:**arm64      
**How docker service was installed:**      

regular

**Comment by sk33z3r** [comment]
In my nginx, I had the proxy pass directive point to `https://DOCKERIP/` and it works mostly without any config modification, but comes with its own problems.

I'd rather have the option to make the container _only_ http/port 80 and handle all the SSL configs myself in my main proxy. I'm not able to upload or get past some SSL errors unless I do a bunch of modifications to the configs that ship with this container.

Not necessarily a bad thing or showstopper, but the app would otherwise have worked "out of the box" if there was an option for an outside reverse proxy friendly setup.

**Comment by dimagoltsman** [comment]
its still cant use https....

**Comment by travelg** [comment]
Any progress on this issue? I can not still nginx reverse proxy https to http port of heimdall. 
Thanks for reply.

**Comment by aptalca** [comment]
Reverse proxy works as long as you use the https port on the backend

**Comment by UbioZur** [comment]
I have the same issue behind traefik.

if I redirect to port 80, for all css/images etc...
`This request has been blocked; the content must be served over HTTPS.`

if I redirect to port 443...
```
400 Bad Request
The plain HTTP request was sent to HTTPS port
```

my dompose file label for traefik
```
- traefik.enable=true
- traefik.http.routers.heimdall.entrypoints=websecure
- traefik.http.routers.heimdall.rule=Host(`heimdall.myserver.com`)
- traefik.http.routers.heimdall.service=heimdall
- traefik.http.services.heimdall.loadbalancer.server.port=443
```

my entry points (for automatic redirection from port 80 to 443)
```
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls: ...
```

so far only heimdall have that issue, not the other services I use.

**Comment by paulianttila** [comment]
> 400 Bad Request
> The plain HTTP request was sent to HTTPS port

I had the same issue and solved it by setting schema to https.

```
- 'traefik.http.services.heimdall.loadbalancer.server.port=443'
- 'traefik.http.services.heimdall.loadbalancer.server.scheme=https'
```

**Comment by JulienFloris** [comment]
To bad it's closed, this issue is still the main reason i'm not using heimdall

**Comment by dimagoltsman** [comment]
same here....   its so easy to fix...

**Comment by xMdb** [comment]
yep

**Comment by j0nnymoe** [comment]
Closing as Heimdall has been reworked/updated since this was initially open. If you're having issues with this behind a reverse proxy, you need to make sure you're setting the APP_URL in the `.env` file.
