### ISSUE TITLE
Jellyfin does not appear on list anymore

### ISSUE THREAD

**Issue by nicktags** [linuxserver/docker-heimdall#62]
## Expected Behavior
Jellyfin should appear on list

## Current Behavior
Not listed at all

## Steps to Reproduce
1. run app

## Environment
**OS:**      Ubuntu Server
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      
docker run -d linuxserver/heimdall

**Comment by Korusuke** [comment]
I think this issue has been long solved and can be closed now
