### ISSUE TITLE
Permissions on the /bootstrap/cache directory (and other directories?)

### ISSUE THREAD

**Issue by amingle4** [linuxserver/docker-heimdall#66]
**Expected Behavior**
The container should start normally with the main page reachable.

**Current Behavior**
I am getting errors in the log: 
  In PackageManifest.php line 168:
  The /var/www/localhost/heimdall/bootstrap/cache directory must be present and writable.

Once that error is resolved (see steps below), I then get "Permission denied" on the main page related to the /var/www/localhost/heimdall/storage/ directory.

**Steps to Reproduce**
1.  I can resolve the cache issue after the container is running by executing this command (this is from Synology Docker):
docker exec -it heimdall php /var/www/localhost/heimdall/artisan config:cache
[Note that if I try to run cache:clear, I get permission denied.]
2.  Once the cache is cleared, I restart the container.
3.  It now gives an error on the main page about Permission denied related to the /var/www/localhost/heimdall/storage/ directory.

In doing a bit of troubleshooting, it looks like the files in the container are owned by root.  However, the PHP user is abc / group abc.  I'm wondering if that's where the disconnect is.  If I do a chown on the /heimdall directory, it seems to fix this particular issue.

**Environment**
 Running on Synology Docker

**Docker Settings File Attached**
For Synology Docker.  This is a JSON file with the settings.
[heimdall.txt](https://github.com/linuxserver/docker-heimdall/files/4941668/heimdall.txt)

**Docker Log Attached**
This picks up after a container restart
[Log.txt](https://github.com/linuxserver/docker-heimdall/files/4941664/Log.txt)

**Comment by Rar9** [comment]
getting the same on a sbc with ubuntu 20.04.  Docker first start is all fine an in can use normally

If I do Docker-composer down and up again and then I also get the same error:

In PackageManifest.php line 168:
                                                                          
The /var/www/localhost/heimdall/bootstrap/cache directory must be present and writable.

**Comment by aptalca** [comment]
permission issue is because you're manually running a php command as root

**Comment by aptalca** [comment]
fill out the issue template about the first issue
