### ISSUE TITLE
Any password works for user login

### ISSUE THREAD

**Issue by tuckshoprn** [linuxserver/docker-heimdall#73]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------
I have enabled an nginx  user and password for this docker instance as detailed in your instructions for the nginx htpasswd:

 docker exec -it heimdall htpasswd -c /config/nginx/.htpasswd <username>

and this part works correctly, bringing up a login box on first entering the url.

Once this is entered, it brings me to the user logon page, for the users as created in heimdall GUI itself as expected.

entering any password in the heimdall user password box allows access to that user.

## Expected Behavior

Upon entering an incorrect password for the heimdall user logon it should deny access
## Current Behavior

It does not matter what password is entered, as long as it is not blank, it allows access to the selected user account

## Steps to Reproduce

Set up new docker instance of heimdall.
set up a nginx htpasswd as follows
docker exec -it heimdall htpasswd -c /config/nginx/.htpasswd <username>

then once logged in using this, go to the users panel, edit the heimdall admin user changing username and entering a new password.

restart the container

enter url

nginx login box presented for the credentials set using "docker exec -it heimdall htpasswd -c /config/nginx/.htpasswd <username>"

once logged in using these, the heimdall user login is presented, pre-populated with the admin users new username
enter anything in the box for password, and it allows access...

## Environment
**OS:** docker running on ubuntu server 20.04 kernel 5.4.0-65-generic
**CPU architecture:** x86_64
**How docker service was installed:**
from the distro repo using apt install docker-compose
running in swarm

## Command used to create docker container (run/create/compose/screenshot)

version: "3.6"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - myvolume:/config
    ports:
      - myport:443
    deploy:
     mode: replicated
     replicas: 1

## Docker logs

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------

          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing... 
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing... 
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing... 
New container detected, installing Heimdall
Setting permissions
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by aptalca** [comment]
.htpasswd has nothing to do with heimdall's user access control or the admin password. .htpasswd is an nginx auth feature, part of the webserver, not related to heimdall at all. When entered correctly, it sets a cookie in the browser. If you want to test that, do incognito window and disable cache

**Comment by tuckshoprn** [comment]
Hi, I understand that, that’s not the bit that’s going wrong. That works as advertised.

It’s the heimdall user logon once you get past the nginx htpasswd that allows any password to log in.

I’m certain I explained that in the text, but apologies if it was unclear.

**Comment by tuckshoprn** [comment]
Has anyone from Linuxserver.io had a look at this yet? I find it worrying that any password will let any user in.

**Comment by ahmedelakkad** [comment]
> Has anyone from Linuxserver.io had a look at this yet? I find it worrying that any password will let any user in.

try and reach them on the discord, they are much more active there. Here is the link: https://discord.gg/YWrKVTn
