### ISSUE TITLE
Allow overridding APP_URL from environment

### ISSUE THREAD

**Issue by michaelkrieger** [linuxserver/docker-heimdall#80]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Setting the environment variable APP_URL should change the root of APP_URL in www/.env

------------------------------

## Desired Behavior
Doing so should generate a .env file with a new APP_URL.  This would enable heimdall to work in reverse proxy scenarios, as a subfolder, on alternate ports, and so on.  For example, https://host.domain:1234/heimdall works if you override the .env file.  Doing it programatically would be extremely useful.

## Current Behavior
Nothing.  There is no way to get this to work at this time.

## Alternatives Considered
Tried things like pathprefix, etc. but heimdall doesn't obey X-Forwarded-* headers
In the simplest, this would be a change in `docker-heimdall/root/etc/cont-init.d/50-config` on launch.
That said, it would be ideal to run on each launch to update the .env file.

**Comment by aptalca** [comment]
`.env` file is in the config folder under `www` and is user customizable

**Comment by michaelkrieger** [comment]
> `.env` file is in the config folder under `www` and is user customizable

Yes, but it's far better to be configurable via the environment variable where a setup is reproducible and all necessary configuration can take place when setting up the container.  It's an easy PR that adds functionality.
