### ISSUE TITLE
Remove port default assignments and set them as not required

### ISSUE THREAD

**Issue by nioakeim** [linuxserver/docker-heimdall#86]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
Heimdall Docker template i believe should honour local configuration changes, especially for port assignments. 

## Current Behavior
Ports are used as default, without exposing them to the host ip. Everytime template is retrieved, port forwarding assignments are re-set from template. In case the default ports 80,443 are already used by another process, app cannot start.

**Comment by j0nnymoe** [comment]
This is a unraid template sync issue, not heimdall issue. https://forums.unraid.net/topic/38619-docker-template-xml-schema/page/5/?tab=comments#comment-1087854
