### ISSUE TITLE
/Concourse/Concourse.php  No such file or directory

### ISSUE THREAD

**Issue by Brettdah** [linuxserver/docker-heimdall#90]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
no error in docker logs <container-name>

## Current Behavior
during container start the commend docker logs <my_containener> display :
```
In ClassLoader.php line 444:

  include(/var/www/localhost/heimdall/vendor/composer/../../app/SupportedApps
  /Concourse/Concourse.php): failed to open stream: No such file or directory

```

## Steps to Reproduce
1. create directory tree (I like my files in a data directory
```
mkdir -p heimdall/data/config
cd heimdall
```
2. create the docker-compose file witrh your favorites editor (I use vi or vim)
``` config
---
version: "2.1"

services:
  heimdall:
    image: linuxserver/heimdall:2.2.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./data/config:/config
    ports:
      - 8082:80
    restart: unless-stopped
```
3. start the container
``` bash
docker-compose up -d
```
4. wait for it to be up then follow the logs ;)
``` bash
docker logs <container_name>
```

## Environment
**OS:** ubuntu 20.04 WSL / synology DSM 7.0.1-42218 Update 2 sur un NAS DS 920+)
**CPU architecture:** x86_64
**How docker service was installed:**
Ubuntu WSL (docker installed via docker desktop for windows with WSL integration)
Docker version 20.10.12, build e91ed57
Docker Compose version v2.2.3

NAS : provided via the sylogy application store and docker-compose updated by downloading the binary
vesrions :
Docker version 20.10.3, build b455053
docker-compose version 1.28.5, build 324b023a

I checked the ```app/SupportedApps/Concourse/```  directory there is  a zip file ... well it's more an html file with zip extention...
you can read a 404 arror when you display the file
[Concourse.zip](https://github.com/linuxserver/docker-heimdall/files/8194264/Concourse.zip)

> THIS IS NOT A ZIP just change the extention it's plain HTML

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
..+++++
..............+++++
writing new private key to '/config/keys/cert.key'
-----
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
New container detected, installing Heimdall
Creating app key. This may take a while on slower systems

In ClassLoader.php line 444:

  include(/var/www/localhost/heimdall/vendor/composer/../../app/SupportedApps
  /Concourse/Concourse.php): failed to open stream: No such file or directory


Setting permissions
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[2022-03-07 02:01:22][1] Processing: App\Jobs\ProcessApps
[2022-03-07 02:01:23][2] Processing: App\Jobs\ProcessApps
[2022-03-07 02:01:23][3] Processing: App\Jobs\ProcessApps
[2022-03-07 02:01:23][3] Failed:     App\Jobs\ProcessApps
```

hope you can help ;)

**Comment by eXsoR65** [comment]
Facing the same issue, though I'm using a raspberry pi 4 with Raspbian 64 bit, Docker 20.10.12, build e91ed57, and Docker Compose ver. 2.2.3.
